### PR TITLE
new feature: freeze function

### PR DESCRIPTION
**Pull request by SeitaHigashi**
add the freeze function.
if freezing, script is not received any command, stop cursor moving.

I'm annoyed the flashing cursor when open hover windows.

### CODE REVIEW

**Comment by gen740** [comment]
Thank you for your PR!

Could you explain the specific use case of this feature?

**Comment by SeitaHigashi** [comment]
When display hover window like lspsaga, the displayed cursor is moving and  removing the cursor columns.
In like this case, I'm annoyed the flushing, I want to keep displayed.

**Comment by gen740** [comment]
Isn't it enough to use `SmoothCursorStop`?

**Comment by SeitaHigashi** [comment]
Even if set the stop, the cursor sign will be removed.
I want remaining.

**Comment by gen740** [comment]
I guess that use case, making an option to SmoothCursorStop like `SmoothCursorStop --keep-signs` is more natural. Since there is already a utility command `SmoothCursorDeleteSigns`.

Currently, there is a bug with switching a hover window(#24). After merging #24 I will create a `--keep-signs` option to `SmoothCursorStop`.

**Comment by SeitaHigashi** [comment]
Nice idea. got it. Thank you.

**Comment by gen740** [comment]
Merged #26.

**Pull request closed without merging**
